# Generated by Django 4.0.3 on 2022-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Set to true when the user have verified its email address. ', verbose_name='verified'),
        ),
    ]
