# Generated by Django 4.0.3 on 2022-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address. ', verbose_name='verified'),
        ),
    ]
