# Generated by Django 4.0.3 on 2022-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
